build:
  image: golang
  commands:
    - go get grubprint.io/...
    - go build grubprint.io
    - go test grubprint.io/...
    - go generate grubprint.io/usda
    - mkdir dist
    - mv grubprint.io dist/
    - cp -R assets dist/
    - ./dist/grubprint.io -keygen
    - mv ./id_rsa* dist/assets/
clone:
  path: grubprint.io
deploy:
  ssh:
    user: daniel
    host: grubprint.io
    commands:
      - sudo systemctl stop grubprint@daniel.service
  rsync:
    user: daniel
    host: grubprint.io
    source: dist/
    target: dist
    delete: true
    recursive: true
    commands:
      - sudo systemctl start grubprint@daniel.service